server:
  port: 8000
spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: false
      routes:
        # 유저 서비스
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users, /users
            - RewritePath=/api/users/(?<segment>.*), /users/$\{segment}
            - CustomFilter
        # 매물 서비스
        - id: property-service
          uri: lb://PROPERTY-SERVICE
          predicates:
              - Path=/api/properties/**
          filters:
              - RewritePath=/api/properties, /properties
              - RewritePath=/api/properties/(?<segment>.*), /properties/$\{segment}
        # 대출 서비스
        - id: loan-service
          uri: lb://LOAN-SERVICE
          predicates:
              - Path=/api/loans/**
          filters:
              - RewritePath=/api/loans, /loans
              - RewritePath=/api/loans/(?<segment>.*), /loans/$\{segment}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
---
spring:
  config:
    activate:
      on-profile: local-cloud
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/